FROM node:13

# Change working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install npm packages 
RUN npm install --production --silent

ENV NODE_ENV production
ENV PORT 3000

EXPOSE 3000

CMD npm start
