FROM node:10-slim as prod

WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install npm packages 
RUN npm install --production --silent

ENV PORT 3000

EXPOSE 3000

CMD ["npm", "run", "start:prod"]

