FROM node:13 as dev

# Change working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install npm packages 
RUN npm install

ENV PORT 3000

EXPOSE 3000

CMD npm start
